//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: MatterHackers.MatterControl.MainOutputDirectory("bin\\Release\\net6.0-windows\\")]

// Generated by the MSBuild WriteCodeFragment class.

